/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aleatorio_instructores;

import javax.swing.JOptionPane;

/**
 *
 * @author DiegoAlonso
 */
public class SorteoCIMM extends javax.swing.JFrame {
    private Sorteo sr;
    private String selFem [];
    private String selMas [];
    
    /**
     * Creates new form SorteoCIMM
     */
    public SorteoCIMM() {
        initComponents();
        sr = new Sorteo();//
        String result = sr.getList();
        if (!result.equalsIgnoreCase("OK")){
            JOptionPane.showMessageDialog(rootPane, result, "Error al leer el archivo", JOptionPane.ERROR_MESSAGE);
        }else{
            jbn_generar_pareja.setEnabled(true);
            jbt_asistencia1.setEnabled(true);
            jbtm_asistencia2.setEnabled(true);
            selFem = sr.getRandom('F');
            selMas = sr.getRandom('M');
            
            jtf_participante1.setText(selFem[0]);
            jtf_participante2.setText(selMas[0]);
            jlbl_faltantes.setText("Numero de Participantes Faltantes: "+sr.getFaltantes());
            jlbl_mujeres.setText("Mujeres Faltantes: "+sr.getInstructoras().size());
            jlbl_hombres.setText("Hombres Faltantes: "+sr.getInstructores().size());
            jlbl_total.setText("Total de Participantes: "+sr.getOrgList().size());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtf_participante2 = new javax.swing.JTextField();
        jbt_asistencia1 = new javax.swing.JButton();
        jbtm_asistencia2 = new javax.swing.JButton();
        jbn_generar_pareja = new javax.swing.JButton();
        jlbl_faltantes = new javax.swing.JLabel();
        jtf_participante1 = new javax.swing.JTextField();
        jlbl_total = new javax.swing.JLabel();
        jlbl_mujeres = new javax.swing.JLabel();
        jlbl_hombres = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Generador de Parejas CIMM 2015");
        setResizable(false);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Participante 1");

        jLabel2.setText("Participante 2");

        jtf_participante2.setEditable(false);
        jtf_participante2.setBackground(new java.awt.Color(255, 255, 255));
        jtf_participante2.setColumns(5);
        jtf_participante2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jtf_participante2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtf_participante2.setToolTipText("Participante Masculino");

        jbt_asistencia1.setText("No Asistio =(");
        jbt_asistencia1.setEnabled(false);
        jbt_asistencia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_asistencia1ActionPerformed(evt);
            }
        });

        jbtm_asistencia2.setText("No Asistio =(");
        jbtm_asistencia2.setEnabled(false);
        jbtm_asistencia2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtm_asistencia2ActionPerformed(evt);
            }
        });

        jbn_generar_pareja.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jbn_generar_pareja.setText("Generar Pareja");
        jbn_generar_pareja.setEnabled(false);
        jbn_generar_pareja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbn_generar_parejaActionPerformed(evt);
            }
        });

        jlbl_faltantes.setText("Participantes:");

        jtf_participante1.setEditable(false);
        jtf_participante1.setBackground(new java.awt.Color(255, 255, 255));
        jtf_participante1.setColumns(5);
        jtf_participante1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jtf_participante1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtf_participante1.setToolTipText("Participante Femenino");

        jlbl_total.setText("Total:");

        jlbl_mujeres.setText("Mujeres Faltantes:");

        jlbl_hombres.setText("Hombres Faltantes:");

        jMenu1.setText("Sorteo");

        jMenuItem1.setText("Reiniciar");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Omitir");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Salir");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtf_participante1)
                            .addComponent(jtf_participante2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbt_asistencia1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jbtm_asistencia2)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlbl_mujeres)
                            .addComponent(jlbl_hombres))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jlbl_total)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jbn_generar_pareja)
                                .addGap(262, 262, 262))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jlbl_faltantes)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf_participante1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jbt_asistencia1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf_participante2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtm_asistencia2)
                .addGap(1, 1, 1)
                .addComponent(jbn_generar_pareja)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbl_faltantes)
                    .addComponent(jlbl_mujeres))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbl_total)
                    .addComponent(jlbl_hombres))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jbt_asistencia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_asistencia1ActionPerformed
        // TODO add your handling code here:
        generarParticipante('F',false);
    }//GEN-LAST:event_jbt_asistencia1ActionPerformed

    private void jbtm_asistencia2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtm_asistencia2ActionPerformed
        // TODO add your handling code here:
        generarParticipante('M',false);
    }//GEN-LAST:event_jbtm_asistencia2ActionPerformed

    private void jbn_generar_parejaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbn_generar_parejaActionPerformed
        // TODO add your handling code here:
        generarParticipante('F',true);
        generarParticipante('M',true);
    }//GEN-LAST:event_jbn_generar_parejaActionPerformed

    private void generarParticipante(char Tipo, boolean estado){
        if (Tipo == 'F'){
            sr.saveAssist(selFem, estado);
            if (sr.getInstructoras().size() > 0){
                selFem = sr.getRandom('F');
                jtf_participante1.setText(selFem[0]);
            }else{
                /* Si no quedan genero femenino se probara a crear pareja de genero masculino*/
                if (sr.getInstructores().size() > 1) {
                    JOptionPane.showMessageDialog(rootPane, "Ya no quedan mas participantes FEMENINOS. \n\n Se generara una pareja de participantes MASCULINOS.", "Error al generar participante", JOptionPane.WARNING_MESSAGE);
                    selFem = sr.getRandom('M');
                    jtf_participante1.setText(selFem[0]);
                }else{
                    /*Si solo queda un participante masculino*/
                    if (sr.getInstructores().size() == 1){
                        JOptionPane.showMessageDialog(rootPane, "Ya no quedan mas participantes FEMENINOS. \n\nSolo queda un ultimo participante MASCULINO. \nFin del Sorteo Gracias por participar.", "Error al generar participante", JOptionPane.INFORMATION_MESSAGE);
                        selMas = sr.getRandom('M');
                        jtf_participante1.setText(selMas[0]);
                        jtf_participante2.setText(selMas[0]);
                    }else{
                        /* Si ya no quedan participantes */
                        JOptionPane.showMessageDialog(rootPane, "Ya no quedan mas participantes.\nFin del Sorteo Gracias por participar.", "Error al generar participantes", JOptionPane.INFORMATION_MESSAGE);
                        jtf_participante1.setText("");
                        jtf_participante2.setText("");
                    }
                    cambiarEstado(false); //Deshabilitar la interfaz Grafica
                }
            }
        }else{
            sr.saveAssist(selMas, estado);
            
            if (sr.getInstructores().size() > 0){
                selMas = sr.getRandom('M');
                jtf_participante2.setText(selMas[0]);
            }else{
                if (sr.getInstructoras().size() > 1) {
                    JOptionPane.showMessageDialog(rootPane, "Ya no quedan mas participantes MASCULINOS. \n\n Se generara una pareja de participantes FEMENINOS.", "Error al generar participante", JOptionPane.WARNING_MESSAGE);
                    selMas = sr.getRandom('F');
                    jtf_participante1.setText(selMas[0]);
                }else{
                    if (sr.getInstructoras().size() == 1){
                        JOptionPane.showMessageDialog(rootPane, "Ya no quedan mas participantes MASCULINOS. \n\nSolo queda un ultimo participante FEMENINO. \nFin del Sorteo Gracias por participar.", "Error al generar participante", JOptionPane.INFORMATION_MESSAGE);
                        selFem = sr.getRandom('F');
                        jtf_participante1.setText(selFem[0]);
                        jtf_participante2.setText(selFem[0]);
                    }else{
                        JOptionPane.showMessageDialog(rootPane, "Ya no quedan mas participantes.\nFin del Sorteo Gracias por participar.", "Error al generar participantes", JOptionPane.INFORMATION_MESSAGE);
                        jtf_participante1.setText("");
                        jtf_participante2.setText("");
                    }
                    cambiarEstado(false); //Deshabilitar la interfaz Grafica
                }
            }            
            
        }
        
        String res = sr.saveList();
        if (!res.equalsIgnoreCase("OK")){
            JOptionPane.showMessageDialog(rootPane, res, "Error al guardar los cambios en el archivo", JOptionPane.ERROR_MESSAGE);
        }

        jlbl_faltantes.setText("Numero de Participantes Faltantes: "+sr.getFaltantes());
        jlbl_mujeres.setText("Mujeres Faltantes: "+sr.getInstructoras().size());
        jlbl_hombres.setText("Hombres Faltantes: "+sr.getInstructores().size());
    }
    
    public void cambiarEstado (boolean estado){
        jbn_generar_pareja.setEnabled(estado);
        jbt_asistencia1.setEnabled(estado);
        jbtm_asistencia2.setEnabled(estado);
        jtf_participante1.setEnabled(estado);
        jtf_participante2.setEnabled(estado);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SorteoCIMM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SorteoCIMM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SorteoCIMM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SorteoCIMM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SorteoCIMM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JButton jbn_generar_pareja;
    private javax.swing.JButton jbt_asistencia1;
    private javax.swing.JButton jbtm_asistencia2;
    private javax.swing.JLabel jlbl_faltantes;
    private javax.swing.JLabel jlbl_hombres;
    private javax.swing.JLabel jlbl_mujeres;
    private javax.swing.JLabel jlbl_total;
    private javax.swing.JTextField jtf_participante1;
    private javax.swing.JTextField jtf_participante2;
    // End of variables declaration//GEN-END:variables
}
